#pragma once

#define BACK_RIGHT_DIREC 1
#define BACK_RIGHT_SPEED 2

#define FRONT_RIGHT_DIREC 3
#define FRONT_RIGHT_SPEED 4

#define FRONT_LEFT_DIREC 5
#define FRONT_LEFT_SPEED 6

#define BACK_LEFT_DIREC 7
#define BACK_LEFT_SPEED 8

#define BACK_RIGHT_CANCODER  11
#define FRONT_RIGHT_CANCODER 9
#define FRONT_LEFT_CANCODER  12
#define BACK_LEFT_CANCODER   10

#define FRONT_LEFT_OFFSET  1745
#define FRONT_RIGHT_OFFSET 1170 
#define BACK_LEFT_OFFSET   534
#define BACK_RIGHT_OFFSET  1608